version: '3.9'

services:
  ui:
    image: 'alerts-ui'
    networks:
      - app-tier
    ports:
      - '80:80'
  api:
    image: 'alerts-dashboard'
    networks:
      - app-tier
    ports:
      - '3000:3000'
      - '8080:8080'
    environment:
      REDIS_HOST: 'redis'
      INRIX_STREAM: 'wss://streams.staging-smartos.com/socket/websocket'
      INRIX_DATASET_SYSTEM_NAME: 'inrix__inrix_traffic_speed_data'
      RAPTOR_API_KEY: ''
  redis:
    image: 'docker.io/bitnami/redis:latest'
    networks:
      - app-tier
    ports:
      - '6379:6379'
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'redis_data:/bitnami/redis/data'

volumes:
  redis_data:
    driver: local

networks:
  app-tier:
    driver: bridge
