apiVersion: v1
kind: Service
metadata:
  name: alerts-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: alerts-api
spec:
  selector:
    app: alerts-api
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: NodePort
