apiVersion: v1
kind: Service
metadata:
  name: alerts-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app: alerts-ui
spec:
  selector:
    app: alerts-ui
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
  type: NodePort
