name: Static Analysis
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    release:
        types: [published]

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
                  cache: 'npm'
            - run: npm install
            - run: npm run build

    Test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
                  cache: 'npm'
            - run: npm install

    start_docker_action:
        runs-on: ubuntu-latest
        needs: [Build, Test]
        steps:
            - name: Kickoff Docker Action
              uses: peter-evans/repository-dispatch@v1
              with:
                  token: ${{ secrets.ORG_PAT }}
                  repository: SmartColumbusOS/alerts-ui
                  event-type: start-publish-docker
                  client-payload: '{"release_tag_name": "${{ github.event.release.tag_name }}", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
